name: Sync IPTV List

on:
  schedule:
    # Ejecutar cada 30 minutos
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-list:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download remote IPTV list
        run: |
          curl -s -o remote_list.m3u "https://ipfs.io/ipns/k2k4r8oqlcjxsritt5mczkcn4mmvcmymbqw7113fz2flkrerfwfps004/data/listas/lista_iptv.m3u"

      - name: Validate M3U file
        run: |
          if [ ! -s remote_list.m3u ]; then
            echo "Error: el archivo descargado está vacío."
            exit 1
          fi

          if ! head -n 1 remote_list.m3u | grep -q "#EXTM3U"; then
            echo "Error: el archivo no parece ser un M3U válido."
            exit 1
          fi

          echo "Validación exitosa: el archivo es un M3U válido."

      - name: Compare and update if different
        run: |
          if [ ! -f lista2.txt ]; then
            touch lista2.txt
          fi

          if ! cmp -s remote_list.m3u lista2.txt; then
            echo "Se detectaron cambios. Actualizando lista2.txt..."
            cp remote_list.m3u lista2.txt
            echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
          else
            echo "No hay cambios en el archivo."
            echo "CHANGES_DETECTED=false" >> $GITHUB_ENV
          fi

      - name: Commit changes if any
        if: env.CHANGES_DETECTED == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update IPTV list from remote source"
          file_pattern: lista2.txt
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com

      - name: Clean up temporary files
        run: rm -f remote_list.m3u

